### PR TITLE
REPL and CLI tool in one

### PR DESCRIPTION
**Pull request by jacktuck**
# Features
- Interactive CLI
- Autocomplete for commands
- Accurate latency which excludes connection time (with verbose `-v` or `--verbose` option)

# Changes
- Now using remit@2
- Arguments are now provided as variadic arguments rather than `-k` options
- JSON is printed in YAML-style

# Todo
 - ~Need option to change remit connection string~
- May need an option to pass non-object e.g. string, number, or array

### CODE REVIEW

**Comment by jpwilliams** [comment]
Is it still possible to trigger this using the old method? Or is it only interactive?

**Comment by jacktuck** [comment]
Only interactive. But i think you can send input straight away

**Comment by jacktuck** [comment]
Actually looks like it might be possible to allow direct invocation too

I'll do some rejigging at some point so leave this open for now :)

**Comment by jpwilliams** [comment]
Ah aces! Yeah as long as you can directly invoke and get a JSON response as it's useful to `pbcopy` that etc as a sample output.

**Comment by jacktuck** [comment]
@jpwilliams I think this works now. I can give a demo tomorrow if the code is not self documenting.

**Comment by jpwilliams** [comment]
Is this working, @jacktuck? Would love to merge if it is! 👍

**Comment by jacktuck** [comment]
@jpwilliams Yeah just need to add some error handling.

Will try and get around to that next week or this weekend.

**Comment by jacktuck** [comment]
Okay think i've sorted out those kinks and added docs etc.

We could publish with alpha tag on npm and see how we get on?

**Comment by jacktuck** [comment]
just published it under `remit-cli-beta` (you'd want 1.1.0) for testing since i don't have access to publish `remit-cli`

**Comment by jacktuck** [comment]
Okay so realized on the beta we probably want to have ```-d, --data [json]          Data (overwrites -k)``` still, so i'll try and add that tonight or ASAP

**Comment by jacktuck** [comment]
Ah crap also got to look into a solution for this
`remit-cli-beta request auth.login email:jack.tuck@crugo.com`

which results in, as it gets expanded
 `email: {jack: { tuck: { @crugo: { com: ""} }}}`

the edge cases 🌊 

```
+  const isArrOrObj = /[,:]/
+  const firstArg = isArrOrObj.test(args[0]) ? expand(args[0]) : args[0]
```

**Comment by jacktuck** [comment]
Also need to allow you to use a remote atm u can only manage them lol

**Comment by jpwilliams** [comment]
How far did you get with it, @jacktuck?

Anything I can do to help?

**Comment by jacktuck** [comment]
@jpwilliams Well more or less finished up with managing list of remotes (will work like nvm / git) to connect to. 

Still not sure what approach will be best for the object expansion oversight  `remit-cli-beta request auth.login email:jack.tuck@crugo.com`

Maybe i should just allow you to forego the object expandng by using quotes `email:"jack.tuck@crugo.com"`

**Comment by jpwilliams** [comment]
I'd leave the object expansion; it's an issue with and without this PR and seeing as we currently use an external lib for it ([expand-object](https://npm.im/expand-object)), the alternative is writing our own which, even if we did it, would be a whole new venture.

Get this coolness going and we'll make that bit better later. 👌

**Comment by jpwilliams** [comment]
Well this is a blast from the past, @jacktuck.

**Pull request closed without merging**
